### ISSUE TITLE
'RevoGridModule' does not appear to be an NgModule class. Angular v16

### ISSUE THREAD

**Issue by kuncevic** [revolist/angular-datagrid#11]
Having issue integrating with In angular v16

```
'RevoGridModule' does not appear to be an NgModule class.(-996002)
component-library-module.d.ts(1, 22): This likely means that the library (@revolist/angular-datagrid) which declares RevoGridModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by dratzinger** [comment]
Guessing this won't be fixed soon, as my PRs here have been open for a year.
I packaged a version that works with Angular 16, which is available on [npm](https://www.npmjs.com/package/@d.ratzinger/angular-datagrid). The stencil proxies might be out of date though (v3.1.8), since building the most recent RevoGrid versions did not produce any usable code.

**Comment by Nabeeh-AlSawaf** [comment]
hoping the team will check this sometime

**Comment by revolist** [comment]
Updated to 4+
New renders, standalone components and full angular support
